import { TextChannel, DMChannel, NewsChannel, ThreadChannel } from 'discord.js';
import { Command, CommandContext } from '../types';
import { addChatMessage, getChatHistory } from '../../db';
import { askBard } from '../../bard';
import { t } from '../../i18n';
import { assertCampaignWrite } from '../utils/campaignWrite';

export const askCommand: Command = {
    name: 'ask',
    category: 'narrativa',
    descriptionKey: 'help.cmd.ask',
    aliases: ['chiedialbardo'],
    requiresCampaign: true,

    async execute(ctx: CommandContext): Promise<void> {
        const { message, args, activeCampaign } = ctx;
        const question = args.join(' ');
        if (!question) {
            await message.reply(t(ctx.locale, 'narrative.askUsage'));
            return;
        }
        if (!await assertCampaignWrite(ctx)) return;

        // Works around TS2339: check whether the channel supports sendTyping
        if ('sendTyping' in message.channel) {
            await (message.channel as TextChannel | DMChannel | NewsChannel | ThreadChannel).sendTyping();
        }

        let answer: string;
        try {
            // PERSISTENT MEMORY HANDLING
            // Dirty dossiers are regenerated by the session pipeline:
            // ASK must not trigger a second AI call.
            const history = getChatHistory(message.channelId, 6); // Recupera ultimi 6 messaggi (3 scambi)
            // askBard already logs the cost of this exchange (prefix [AskBard][COST])
            // and persists it to ai_usage_log right away — no need to duplicate it here.
            const result = await askBard(activeCampaign!.id, question, history);
            if (!result.succeeded) throw new Error('Ask provider failed');
            answer = result.answer;
        } catch (err) {
            console.error("Errore chiedialbardo:", err);
            await message.reply(t(ctx.locale, 'narrative.askError'));
            return;
        }

        try {
            // Save to the DB
            // The assistant turn carries the asker's id too: it quotes them, and
            // an erasure that took the question but left the answer would be a
            // half-deletion.
            addChatMessage(message.channelId, 'user', question, message.guildId ?? undefined, message.author.id);
            addChatMessage(message.channelId, 'assistant', answer, message.guildId ?? undefined, message.author.id);

            await message.reply(answer);
        } catch (err) {
            // The AI action succeeded and has already been charged: a later Discord/DB
            // error must not be treated as a failure of the question.
            console.error("Errore pubblicazione risposta chiedialbardo:", err);
        }
    }
};
